import Navigation from "@/app/components/Navigation/NavigationWrapper";
import "./globals.css";
import { Quicksand, Playfair_Display } from "next/font/google";
import Footer from "@/app/components/Footer";

const quickSand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quickSand",
});
const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playFair",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${quickSand.variable} ${playfairDisplay.variable}`}
    >
      <body className="font-body">
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
